### ISSUE TITLE
License - Liquor License - Status Issue on Application Creation

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1004]
Upon initial creation of a Liquor License application, the application begins in an Active status. Upon resulting the Completeness Check (with any result) the license Status move to Processing. This issue seems to occur inconsistently. I have seem it happen on some liquor licenses but not all.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58642640-bf3e1680-82cb-11e9-9b4b-dc57ba871389.png)

![image](https://user-images.githubusercontent.com/31770504/58642726-e4cb2000-82cb-11e9-97b1-dd1faf6bd139.png)

![image](https://user-images.githubusercontent.com/31770504/58642669-cf55f600-82cb-11e9-9195-5eae02182c27.png)

![image](https://user-images.githubusercontent.com/31770504/58642750-ebf22e00-82cb-11e9-8313-a7e23832688d.png)

**Comment by calequin** [comment]
fixed in preprod and test

**Comment by JuanitaMiles** [comment]
Appears fixed. 

![image](https://user-images.githubusercontent.com/31770504/59373597-fc68c680-8d17-11e9-97af-7147103e1ae9.png)

**Comment by JuanitaMiles** [comment]
for some reason not fixed anymore. Starting out as Active.

![image](https://user-images.githubusercontent.com/31770504/59439596-8c177f00-8dc3-11e9-8c14-bd0040336476.png)

**Comment by calequin** [comment]
fixed in preprod

**Comment by JuanitaMiles** [comment]
Appears fixed upon entering Completeness Check milestone. The Application Added milestone still starts as Active but this only shows on the logs tab. Closing the issue for now.

![image](https://user-images.githubusercontent.com/31770504/59602757-94c6c880-90d5-11e9-8671-e37a8c90b60c.png)
