### ISSUE TITLE
License - Liquor License - Expiration Dates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1014]
If I created a license on 5/30/2019 why are my Expires and GRace Exp dates set in the past (4/1/2019)?

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58646916-6cb52800-82d4-11e9-85a8-0fdc16c7b56d.png)

**Comment by calequin** [comment]
fixed NRD formula in preprod and test

**Comment by JuanitaMiles** [comment]
Not fixed. The Expires and Grace Exp dates are still showing the same date in the past. The Next Renewal date now populates with a date in the future, which is good, however, if a license has gone through a renewal once already should the Last Renewal date populate with the most recent renewal?

![image](https://user-images.githubusercontent.com/31770504/59606125-5550aa00-90de-11e9-8389-cce7a919c823.png)

![image](https://user-images.githubusercontent.com/31770504/59606153-6e595b00-90de-11e9-8156-8cd840917ed3.png)

**Comment by calequin** [comment]
fixed. added milestone called renewal license Issued. this sets a renewal license status date on the application. The last renewal date will populate with the most recent renewal date in the past.

**Comment by JuanitaMiles** [comment]
The expiration date should always be 4/30 of the next year.

**Comment by calequin** [comment]
fixed expiration date formula in test

**Comment by dhenry-KCI** [comment]
Confirmed fixed. Closed.
