### ISSUE TITLE
R4C-Electric Application-Residential Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1078]
There are multiple options under the Electric Residential Options that are not applicable to Residential work. All the options with the red x next to it need to be deleted. Also Demolition needs to be capitalized to match the others.-AW
![image](https://user-images.githubusercontent.com/47611580/59106588-c638da80-8904-11e9-8e34-48982d68a428.png)
![image](https://user-images.githubusercontent.com/47611580/59106601-cd5fe880-8904-11e9-8677-4fedab44dc6e.png)
![image](https://user-images.githubusercontent.com/47611580/59106615-d486f680-8904-11e9-9db3-02cda085b392.png)

Also the description box/options need to be deleted. We do not use it for permits. 
![image](https://user-images.githubusercontent.com/47611580/59107267-3eec6680-8906-11e9-8335-5ba2c5703221.png)

The Declared Valuation and Square Footage can be deleted, they are not needed for electric permits. 
![image](https://user-images.githubusercontent.com/47611580/59107507-cdf97e80-8906-11e9-9d3c-332564c976a0.png)

The Occupancy type on the first page of the application should drive the details page to only show the Residential options. not both the Residential and Non Residential options. 
![image](https://user-images.githubusercontent.com/47611580/59107609-0ac57580-8907-11e9-8aad-f6f7c61659a1.png)
![image](https://user-images.githubusercontent.com/47611580/59107750-4b24f380-8907-11e9-97f2-209f08bb1f53.png)

The Grids do not save either. and therefore do not transfer over to ips.
![image](https://user-images.githubusercontent.com/47611580/59108056-09487d00-8908-11e9-9a92-a92e68e16ee7.png)
![image](https://user-images.githubusercontent.com/47611580/59108046-064d8c80-8908-11e9-9602-dd8073e2c4dd.png)
![image](https://user-images.githubusercontent.com/47611580/59108229-71975e80-8908-11e9-8749-b5987992f39c.png)

**Comment by calequin** [comment]
fixed in test
removed declared valuation contrainst = Not present
removed square footage constraint = not present
Detail Pages - this detail page is one detail page for the application therefore both nonres and res automatically is displayed. The only fix would be to add another detail page per residential and non residential. This will cause a good amount of formula workflow rework.
Grids not saving - has been fixed in test by switching the key column saving, then switching it back to the original key column.

**Comment by ABonomo21** [comment]
That's fine for leaving the Non res and Res details boxes on the same detail page-confirmed with Ashlye-AW

this whole issue is Partially Fixed:

Description box is gone-fixed
![image](https://user-images.githubusercontent.com/47611580/59292469-286a4600-8c4b-11e9-8039-81253093f974.png)

Grids are saving-fixed
![image](https://user-images.githubusercontent.com/47611580/59292799-c2ca8980-8c4b-11e9-9736-2bed19866c56.png)

Not sure how I can test the electrical detail "add rows", they are still showing the ones that should be expired in both R4C and test. and the layout in IPS test is different than R4C.
![image](https://user-images.githubusercontent.com/47611580/59292620-6a938780-8c4b-11e9-9556-338dba3f233f.png)
![image](https://user-images.githubusercontent.com/47611580/59292698-8e56cd80-8c4b-11e9-88d9-9dbd25edfa3b.png)

**Comment by ABonomo21** [comment]
@calequin  For the "add rows" I meant that I can't test that issue in IPS because the issue with the grid not saving was on R4C. So we need the grid to save on R4C so it will then transfer to IPS.  It's been working good since I logged this but i will confirm on Mon (6/24) to make sure I'm remembering correctly-AW

**Comment by ABonomo21** [comment]
Fixed-Grid is saving over to IPS from R4C on both res and non res elec permits-AW
![image](https://user-images.githubusercontent.com/47611580/60102478-c706a480-972b-11e9-8ac8-2e6c4bf18c13.png)
![image](https://user-images.githubusercontent.com/47611580/60102790-62981500-972c-11e9-9325-873d9d7fd000.png)
