### ISSUE TITLE
R4C Plumbing Details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1084]
Residential Plumbing Permit Details Permit#245687-MCoffman

"Declared Valuation" is not a required field on Plumbing Permits
![image](https://user-images.githubusercontent.com/47611580/59105981-3ba3ab80-8903-11e9-8bf6-9515d7e8a729.png)

Should say "Description of Work"
![image](https://user-images.githubusercontent.com/47611580/59105893-fda68780-8902-11e9-93d8-c9556c3d3443.png)

Dwelling Details:
Can we change the wording on these to be more clear for the customer
1&2 FAM ATTCHD MORE THAN 3000 SF W/ GAS
1&2 FAM ATTCHD MORE THAN 3000 SF NO GAS
1&2 FAM ATTCHD 3000 SF OR LESS W/ GAS
1&2 FAM ATTCHD 3000 SF OR LESS NO GAS
SFD 4000 SF TO 6500 SF W/ GAS
SFD 4000 SF TO 6500 SF NO GAS
SFD 4000 SF OR LESS W/ GAS
SFD 4000 SF OR LESS NO GAS
SFD 6500 SF OR MORE W/ GAS
SFD 6500 SF OR MORE NO GAS
![image](https://user-images.githubusercontent.com/47611580/59110655-95a96e80-890d-11e9-8807-fe228934319d.png)
![image](https://user-images.githubusercontent.com/47611580/59110975-2bdd9480-890e-11e9-9a84-0c95c1e81669.png)

This should only be available in the back office
![image](https://user-images.githubusercontent.com/47611580/59109584-4a8e5c00-890b-11e9-86a3-2b4242209043.png)

Residential Fixture Details:
Can we add: Demolition
Can we remove: Drinking Fountain
![image](https://user-images.githubusercontent.com/47611580/59110380-ff754880-890c-11e9-9faa-ec7ad7bcb411.png)

Gas Details: Can we change this to say "Replacement of Single Fixture"; we think the wording may confuse customers
![image](https://user-images.githubusercontent.com/47611580/59108847-dd2dfb80-8909-11e9-9afb-96895154aba2.png)

This is a Residential Plumbing Permit this should not be visible 
![image](https://user-images.githubusercontent.com/47611580/59112054-431d8180-8910-11e9-8af5-9e84bad95ef6.png)

Not all of the Grids are saving after you fill them in
![image](https://user-images.githubusercontent.com/47611580/59112228-97286600-8910-11e9-9ee0-9119d42d0ee7.png)

![image](https://user-images.githubusercontent.com/47611580/59112176-7c55f180-8910-11e9-9697-a61245118709.png)

**Comment by calequin** [comment]
fixed in test
removed declared valuation = not present
fixed description of work - in trnaslation override for r4c
Dwelling detail description fixed in test = in RCDM
homeowners test results - show in portal = false
fixed grid saving
Removed drinking fountain and added demolition
Reword - replacement of single fixture
detail pages - residential and nonresidential are in the same detail page thereofore they are visible to the customer. In order to make this dynamic we would need to create a new detail page which will likely cause workflow changes and configuration changes.

**Comment by ABonomo21** [comment]
MCoffman-Don't see corrections in Test or R4C. Some Corrections need to stay in the back office but be removed from R4C. I'm not sure how to check that in Test. 

Not sure how this will transfer over into R4C-Declared Valuation is still visible in test
![image](https://user-images.githubusercontent.com/47611580/59203616-f08cd100-8b6c-11e9-9261-abd2346a47e6.png)

Description of Work is corrected

Dwelling Details-Not corrected in test
![image](https://user-images.githubusercontent.com/47611580/59203945-a35d2f00-8b6d-11e9-995c-f5fe4b6bc970.png)

Homeowner Test Status-Still Visible in test, need to see it in R4C
![image](https://user-images.githubusercontent.com/47611580/59204057-d30c3700-8b6d-11e9-8a26-6700db48c257.png)

Residential Plumbing Fixture Details
Drinking Fountain is still Visable
Demolition Not Added
![image](https://user-images.githubusercontent.com/47611580/59204168-1070c480-8b6e-11e9-8d7e-421bd1df3cda.png)

Rewording of Replace/New Single Fixture not corrected
![image](https://user-images.githubusercontent.com/47611580/59204229-339b7400-8b6e-11e9-878a-06563e40aea0.png)

**Comment by calequin** [comment]
Fixed in preprod

**Comment by ABonomo21** [comment]
-MCoffman

Under Plumbing Fixture Detail this needs to stay "Replace/New Single Fixture"
![image](https://user-images.githubusercontent.com/47611580/59287383-8a24b300-8c3f-11e9-9d8e-811d307489a4.png)

Under Gas Details this needs to be fixed to say "Replacement of Single Fixture"
![image](https://user-images.githubusercontent.com/47611580/59287176-269a8580-8c3f-11e9-85b8-c59043354543.png)

Can we add a note at the top of the Details Page that says "Only fill in grids pertaining to your scope of work"

**Comment by ABonomo21** [comment]
the only issue that was not resolved is the replace single fixture under gas details
![image](https://user-images.githubusercontent.com/47611580/59448431-1d422200-8dd3-11e9-826a-073baa4638ab.png)


Also this comment was not added

![image](https://user-images.githubusercontent.com/47611580/59448496-3c40b400-8dd3-11e9-962f-47be5c1e4d81.png)

**Comment by calequin** [comment]
fixed in preprod
![image](https://user-images.githubusercontent.com/47603568/59524734-437ec500-8e9a-11e9-9067-11b4938ba828.png)

**Comment by ABonomo21** [comment]
Corrected.
