### ISSUE TITLE
Trade License - ELEC - Access Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1234]
Why would I not be able to result the Completeness Check review on this ELEC trade license? The permissions for everything under the Admin role is checked. However, it appears as though the License Type that actually has the COMPLETE review under it is 'ELECB' which is not an available license type when creating an application. The ELEC type is available, and under Access Control this type only has signature reviews available. 

I have also confirmed that I have the Admin Role assigned and I have all of the required licenses.

**This is NOT a security issue KCI would know how to fix, Infor must provide guidance or fix it.**

![image](https://user-images.githubusercontent.com/31770504/59924324-81806980-9403-11e9-8ab3-690330e8202f.png)

![image](https://user-images.githubusercontent.com/31770504/59924560-fd7ab180-9403-11e9-9b66-cd4b71311a52.png)

![image](https://user-images.githubusercontent.com/31770504/59924388-a07efb80-9403-11e9-8d38-754cb4789076.png)

![image](https://user-images.githubusercontent.com/31770504/59924731-62cea280-9404-11e9-907f-8a562a94cfa1.png)

**Comment by megisys** [comment]
This is fixed in PreProd. For ADmin Role Only

**Comment by JuanitaMiles** [comment]
I've shut down my browser and tried again. Still cannot record the result. Where are the Create, Record, Review Detail, and View Review sub-options on the COMPLETE review here?

![image](https://user-images.githubusercontent.com/31770504/59926530-7d0a7f80-9408-11e9-9f45-deac85fd027a.png)

**Comment by goggansd** [comment]
In PreProd environment, created access role tree for ELEC COMPLETE review to match COMPLETE review for ELECB. Altered Admin access role to have these new permissions. Verified Admin role can record results for COMPLETE review for ELEC license E244406.

![image](https://user-images.githubusercontent.com/28841997/59932493-471fc800-9415-11e9-91e9-da49460e9f55.png)

**Comment by dhenry-KCI** [comment]
Was able to result the completeness check but could not view the eletrical detail page. Receive the following:

![image](https://user-images.githubusercontent.com/4129185/60041907-7723d100-968a-11e9-93a9-697588ca0462.png)

**Comment by dhenry-KCI** [comment]
@calequin -we were discussing this item yesterday- Reassigning as a reminder.

**Comment by megisys** [comment]
Fixed in TEST

**Comment by JuanitaMiles** [comment]
Was able to result Completeness Check. When trying to open the Confirm License Details page to satisfy this status check at the Awaiting Renewal Details milestone. I get this error. Tried this in PreProd. (AP # E244410)

![image](https://user-images.githubusercontent.com/31770504/60207498-0b756b80-9824-11e9-9618-81bdab89b8ab.png)

**Comment by ABonomo21** [comment]
will double check during end to end- appears to be okay
