### ISSUE TITLE
R4C-Plumbing Details Page-Section Complete box

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1246]
The Section Complete Box and the Parent Required Box should be at the very bottom of the application in R4C, rather than in the middle of the Non Res and Res options.-AW

![image](https://user-images.githubusercontent.com/47611580/60110818-b7db2300-973a-11e9-9172-511c234ae1c6.png)

**Comment by calequin** [comment]
fixed in preprod and test.

**Comment by ABonomo21** [comment]
Partially fixed. The Section Complete box is in the correct place but the Parent Required checkbox should be back office only.-AW
![image](https://user-images.githubusercontent.com/47611580/60121773-d567b700-9751-11e9-8093-fbcc2cad40c8.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/60122456-38a61900-9753-11e9-94a0-fa3bb398f9cb.png)
