### ISSUE TITLE
License - Liquor License - Renewal Review Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1328]
I resulted the RENEWAL_CK review with Resubmit and the application progressed to Renewal Review Resubmit like it should have. However, once I completed that Applicant Actions page, the application went straight to Active. No second cycle RENEWAL_CK review generated. 

At this point no renewal fees were manually added to the application yet. I was going to add them on the second cycle renewal review but had no opportunity.

Tested this in TEST environment due to the error mentioned in issue #1324 

![image](https://user-images.githubusercontent.com/31770504/61149496-4aa3ed80-a4af-11e9-84a1-f89e10c2d2df.png)

![image](https://user-images.githubusercontent.com/31770504/61149579-758e4180-a4af-11e9-843e-216106d835e8.png)

**Comment by calequin** [comment]
fixed in dev.

**Comment by dhenry-KCI** [comment]
@calequin - still having an issue with this one. Just checked. See LI244341

**Comment by calequin** [comment]
Added a fees condition to force the staff to add manual fees on a renewal

**Comment by JuanitaMiles** [comment]
@dhenry-KCI - The Renewal Review milestone SOP instructions on the Check Status window indicates that renewal fees must be added manually BEFORE approving the RENEWAL_CK review otherwise the application will move to Active without fees. Christian added a condition that you will have to approve on the Conditions tab to act as a verification that liquor staff has either added the correct renewal fees or no additional fees are required. Please retest following these procedures.

I remember confirming with Penny that this will be a manual fee addition, not automatic.

**Comment by JuanitaMiles** [comment]
@calequin - Can we make sure we apply the rule that if the RENEWAL_CK review is resulted with a resubmit, the system ignores the fee condition status check? Just like with other permit/planning applications they may need a resubmittal of details before satisfying other status checks.

**Comment by calequin** [comment]
Condition approval on license requires a yes answer each time since the fee condition is added. The only way around this is by removing the condition and using SOP to make sure staff inputs fees. bypass formulas dont work well with conditions

**Comment by TaraF** [comment]
This is still not working correctly, Christian will be investigating.  AP# tested was 250699.

**Comment by calequin** [comment]
fixxed. removed condition since conditions do not work well on applications that have a renewal cycle more than once. Part of the renewal review will be to add fees to the application

**Comment by dhenry-KCI** [comment]
confirmed fixed.
