### ISSUE TITLE
R4C - Fees Due (Excel Issue #61)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1347]
please get rid of the minimum balance due field. all fees are due at the same time we do not take partial payment. 

![image](https://user-images.githubusercontent.com/47611580/61796796-28d23100-adf4-11e9-8bc0-73ad652270c6.png)

**Comment by calequin** [comment]
From my initial research the minimum due balance looks to be a hard coded field in the product in this release. Since Frederick does not do minimum balances/billing, the amount will always reflect the same as the unpaid balance.  Putting this on the excel sheet for development to look at.

**Comment by calequin** [comment]
config switch will be added to the 19.9 release

**Comment by ABonomo21** [comment]
why is this marked as a nice to have @dhenry-KCI we should not have minimum fees as it is not applicable to our processes

**Comment by calequin** [comment]
fixed.,

**Comment by dhenry-KCI** [comment]
Minimum fee still showing up in the application details on the applicants dasboard.

![image](https://user-images.githubusercontent.com/4129185/65448994-08305280-de08-11e9-8925-6a88aa3ef99f.png)

**Comment by calequin** [comment]
fixed. removed minimum fee from the My prjects view and set it to false in r4c.

**Comment by dhenry-KCI** [comment]
Verified corrected under all payment screens on R4C. Project PL245466. AREED
