### ISSUE TITLE
Mobile- In field notification

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1429]
notification not working- server error message- object reference not set to an instance of an object

**Comment by calequin** [comment]
need to set up notification on hansen8 test environemnt after hours

**Comment by calequin** [comment]
fixed but set as enabled = false to avoid mass text messages to live customers. Need to set mobile phone to a generic line.

**Comment by ABonomo21** [comment]
use ashlye's work phone 301.471.2677
not fixed still got server error- no active methods were found for notification type inspstsupd

**Comment by calequin** [comment]
@ABonomo21  @dhenry-KCI  this will need to be tested in a specific time where I can turn it back on and make sure ashlye's mobile is set. Please let me know when we can jump on a call.

**Comment by ABonomo21** [comment]
sms works 
![image](https://user-images.githubusercontent.com/47611580/68322172-f42b7200-0090-11ea-838c-e117dd48cb57.png)
