### ISSUE TITLE
Use Permit - Home Occupation - DOLS Review Description Spelling Error

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1599]
Processing a Home Occupation (Use Permit) and the DOLS review description has incorrect spelling of DEPARTMENT. This shows to the applicant on Rhythm for Civics and should be updated.

![image](https://user-images.githubusercontent.com/31770504/63288771-8a6aab80-c28b-11e9-9697-d5caededba7d.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Not fixed.

![image](https://user-images.githubusercontent.com/31770504/64362814-2ced9300-cfdd-11e9-88f0-d1f6edc39816.png)

**Comment by calequin** [comment]
fixed. accidentally fixed the wrong label.

**Comment by ABonomo21** [comment]
fixed 9.5.19 ab
![image](https://user-images.githubusercontent.com/47611580/64369292-03873400-cfea-11e9-96d7-2062fbca36e4.png)
