### ISSUE TITLE
Planning - SITE Plan Type I - Health Review populated in error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#160]
Health is Conditionally Add on a Site Plan Type 1. Parcel Details shows public water and sewer so Health Review should not generate.
![image](https://user-images.githubusercontent.com/4129185/53662525-1717a380-3c31-11e9-97ec-7f37ce6c44c8.png)
![image](https://user-images.githubusercontent.com/4129185/53662550-272f8300-3c31-11e9-8fad-4ded54624952.png)
![image](https://user-images.githubusercontent.com/4129185/53662640-69f15b00-3c31-11e9-934f-8821843ff732.png)

**Comment by megisys** [comment]
Fixed and Ready to Test

**Comment by dhenry-KCI** [comment]
This is not fixed. Health review still auto populated on a parcel with public water/sewer.


![image](https://user-images.githubusercontent.com/4129185/53740988-67764780-3e63-11e9-9339-f888e25ee080.png)

**Comment by dhenry-KCI** [comment]
Fixed MW

![image](https://user-images.githubusercontent.com/4129185/53744288-b4a9e780-3e6a-11e9-8dad-a804d3bc2f6f.png)
