### ISSUE TITLE
planning-plat-mylar fee notification 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1682]
didnt get a fee notification at awaiting paperwork milestone when $59 redecoration fee is due.

![image](https://user-images.githubusercontent.com/4129185/63951612-1038e480-ca4c-11e9-9b1b-05193523d2e6.png)

MW

**Comment by dhenry-KCI** [comment]
also applies to school construction fees, 


![image](https://user-images.githubusercontent.com/4129185/63954105-8e978580-ca50-11e9-9136-5c22d3cc8a29.png)


MW

**Comment by dhenry-KCI** [comment]
didnt get notification.  The notification in the log below was for the initial fee.

![image](https://user-images.githubusercontent.com/4129185/64177625-e7d72e80-ce2d-11e9-87aa-9d500fd7a413.png)

![image](https://user-images.githubusercontent.com/4129185/64177659-f7567780-ce2d-11e9-9a85-638c606b0b36.png)


MW

**Comment by megisys** [comment]
WebServices Issue - Need Notification Types Set up in Webservices. All of them.

**Comment by calequin** [comment]
fixed notification

**Comment by dhenry-KCI** [comment]
still not working.


![image](https://user-images.githubusercontent.com/4129185/64341932-762aec00-cfb7-11e9-894e-a2824b7763f7.png)


MW

**Comment by megisys** [comment]
Rather than have 2 notifications. I added outstanding fees lines to the Awaiting Paperwork Notification. Are you ok with this ?

**Comment by dhenry-KCI** [comment]
thats fine.  The fee didnt come through though.

![image](https://user-images.githubusercontent.com/4129185/64362923-64f4d600-cfdd-11e9-9708-457ae92bc5e7.png)

![image](https://user-images.githubusercontent.com/4129185/64362934-6e7e3e00-cfdd-11e9-933d-e8bb27a63052.png)


MW

**Comment by dhenry-KCI** [comment]
@mmbanong - see thread. Add fee to notification

**Comment by mmbanong** [comment]
The Notification already has the fees definition. I  will investigate why it's not getting displayed

![image](https://user-images.githubusercontent.com/47392173/64433027-ae036380-d08b-11e9-8931-164a732436d2.png)

**Comment by mmbanong** [comment]
I got the payment Notification.
Take a look at the Log. Awaiting Apllicant Payment milestone come before Awaiting PaperWork. So there shouldn't be any unpaid fees

![image](https://user-images.githubusercontent.com/47392173/64435296-3c79e400-d090-11e9-950a-aa74895c2a3c.png)

![image](https://user-images.githubusercontent.com/47392173/64434933-a2b23700-d08f-11e9-82a7-4f8df9365813.png)

![image](https://user-images.githubusercontent.com/47392173/64435418-72b76380-d090-11e9-8134-506092479b22.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - if there are never any fees that would be unpaid - let's remove the "Currently there are $0.000 unpaid fees."

**Comment by mmbanong** [comment]
We will never have a value for the current fees at the awaiting paperwork milestone as long the fees are paid in the previous milestone. The stakeholders need to make a decision on removing the unpaid fees

![image](https://user-images.githubusercontent.com/47392173/65150240-b778be00-d9f1-11e9-8241-57fd9e30a844.png)

**Comment by mmbanong** [comment]
Expired the notification at awaiting paperwork milestone per Dustin
	Awaiting Applicant Payment should be the only notification

**Comment by dhenry-KCI** [comment]
The notification that was received under PL245442 does not provide the mylar fee of $118 that is the current unpaid amount. Notification says. $0.0000. 
Is the notification firing just before the fees are added? Maybe? AR
![image](https://user-images.githubusercontent.com/4129185/65713939-301df100-e068-11e9-8331-3076bd7a565b.png)

**Comment by mmbanong** [comment]
The notification at awaiting paperwork milestone has been expired per Dustin
Awaiting Applicant Payment is the only notification

![image](https://user-images.githubusercontent.com/47392173/66397237-5ff2c000-e9a9-11e9-88af-1d81accb6ff8.png)

![image](https://user-images.githubusercontent.com/47392173/66397452-dabbdb00-e9a9-11e9-858e-a57ae381b165.png)

**Comment by dhenry-KCI** [comment]
PL252074 - NO Notification received when going through R4C/IPS/PDOX

![image](https://user-images.githubusercontent.com/4129185/66953826-3121bd00-f02d-11e9-9322-6f5f89ca7bbb.png)

**Comment by dhenry-KCI** [comment]
failed PL252145

![image](https://user-images.githubusercontent.com/4129185/67416672-3931ad80-f595-11e9-9139-022ce533332a.png)


MW

**Comment by megisys** [comment]
Can we test this one more time.. I ensured the Notifications are set up in WEbServices

**Comment by dhenry-KCI** [comment]
still not getting notification. the notify log below was for the initial fee.


![image](https://user-images.githubusercontent.com/4129185/67962725-e3cc5080-fbd3-11e9-8f5b-d3ff68c174ee.png)


MW

**Comment by megisys** [comment]
AVOLVE Account had no email address set..

**Comment by dhenry-KCI** [comment]
fixed.  email being sent to avolve.  to go to applicant at go live

![image](https://user-images.githubusercontent.com/4129185/68329849-2abcb900-00a0-11ea-9983-c0be51abe779.png)

![image](https://user-images.githubusercontent.com/4129185/68329872-37411180-00a0-11ea-80a8-c169f1bcf48b.png)

MW
