### ISSUE TITLE
Building Permits - BPREVIEW AP Not Going Through PDOX

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1856]
BPReview permits are getting an error when trying to go through PDox. Most likely because its not pulling the whole id number. It's only bringing over the B instead of the BPMH.

![image](https://user-images.githubusercontent.com/31770504/65171276-77790180-da18-11e9-9c20-36fe174d476b.png)

**Comment by JuanitaMiles** [comment]
@megisys Tried this again this morning...I also noticed that the reference number is not just missing the additional letters "PMH" but the number is totally different from what is on the BP Review permit.

![image](https://user-images.githubusercontent.com/31770504/65243338-291a4000-dab6-11e9-9f90-2bc6160f0b12.png)

![image](https://user-images.githubusercontent.com/31770504/65243570-8ca46d80-dab6-11e9-853c-b0ca515263d7.png)

**Comment by megisys** [comment]
I fixed this Still not happening. Might need to reach out to Robert here

**Comment by megisys** [comment]
I fixed the numbering piece

**Comment by JuanitaMiles** [comment]
These BPREVIEW applications were processed 10:39; 10:36; and 10:46 and I still do not see them in PDox. 

![image](https://user-images.githubusercontent.com/31770504/65257410-27a94180-dacf-11e9-8c34-4cbe9457c68c.png)
![image](https://user-images.githubusercontent.com/31770504/65257445-368ff400-dacf-11e9-9c87-70dd5038558c.png)

**Comment by JuanitaMiles** [comment]
Processed this through batch manager at 14:06 (2:06). It's now 2:19 and it's still not in ProjectDox

![image](https://user-images.githubusercontent.com/31770504/66508829-de318e00-ea9f-11e9-8532-fb70477659f4.png)

**Comment by RS-Avolve** [comment]
I suspect the reason the Blanket Plan Review is not creating in ProjectDox is due to a name mismatch between the IPS side and the ProjectDox side.  On the ProjectDox side I created an application type called "Blanket Plan Review".  I suspect this is named something different on the IPS side.   Please verify what the name of the App Type is on the IPS side and let me know.  I have verified with Alejandro that there is nothing he has to do to make this work.

**Comment by dhenry-KCI** [comment]
@RS-Avolve See screenshot below for naming convention

![image](https://user-images.githubusercontent.com/4129185/67233475-458cfd80-f411-11e9-8569-8819ec4672b0.png)

**Comment by RS-Avolve** [comment]
I changed the name of the Application Type in ProjectDox from "Blanket Plan Review" to BPREVIEW.  I made this change in both TEST and PROD.  Please test this to verify it works.  Thanks.

**Comment by JuanitaMiles** [comment]
Went through in PDox when we tested on 11/5.
