### ISSUE TITLE
License - Liquor License - Preliminary Review Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1887]
After the Awaiting Document Upload milestone I went straight to Preliminary Review but it generated two PRELIM reviews at once. It looks like the milestones are not progressing in the right order from looking at the logs tab.

![image](https://user-images.githubusercontent.com/31770504/65435930-49683880-ddef-11e9-8874-9f03d4ff82be.png)

![image](https://user-images.githubusercontent.com/31770504/65435960-571dbe00-ddef-11e9-9afb-90e112b802c2.png)

**Comment by calequin** [comment]
fixed. next milestone progression formula

**Comment by JuanitaMiles** [comment]
Not fixed. Resulted the 1st Preliminary Review with Resubmit and now the application is not progressing at all. When I check the Check Status button, there are no status checks that need to be satisfied.

![image](https://user-images.githubusercontent.com/31770504/66053165-ce460700-e4ff-11e9-946e-fb858da3ef2d.png)

![image](https://user-images.githubusercontent.com/31770504/66053183-d9009c00-e4ff-11e9-9665-4cebbcca8e19.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Prelim review progressed properly.

![image](https://user-images.githubusercontent.com/31770504/66506094-aaa03500-ea9a-11e9-9ba4-30cda066c740.png)
