### ISSUE TITLE
Use Permits - Home Occupation - Re-Inspection Fee Due Notification Not Sending

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1934]
I am not receiving re-inspection fee due notifications when a re-inspection fee generates on Home Occupation permits. This notification should be sending.

![image](https://user-images.githubusercontent.com/31770504/66049964-575a3f80-e4fa-11e9-93e7-c4246efcd4fc.png)

**Comment by mmbanong** [comment]
This has been addressed under #1978

**Comment by mmbanong** [comment]
#1974 is for Land Use . I will work on this one now

**Comment by JuanitaMiles** [comment]
Not fixed. I did not get a notification.

![image](https://user-images.githubusercontent.com/31770504/66505670-cbb45600-ea99-11e9-91f0-2cdc023b4d78.png)

![image](https://user-images.githubusercontent.com/31770504/66505693-d7078180-ea99-11e9-919c-b58fcbcc36c9.png)

**Comment by mmbanong** [comment]
Removed the notification at the awaiting Reinspection Payment milestone and added new formula to evaluate the added fees and only send the notification if the fee is a Home Occupation re-inspection fee
Please try again

**Comment by JuanitaMiles** [comment]
cannot test this. getting an error when trying to result an inspection.

![image](https://user-images.githubusercontent.com/31770504/66761808-bdd44b80-ee72-11e9-8c4c-a7f2e2278b37.png)

**Comment by ABonomo21** [comment]
dan fixed 10.15.19
![image](https://user-images.githubusercontent.com/47611580/66855675-b5067700-ef51-11e9-9980-b5c2e3e74e03.png)
