### ISSUE TITLE
License - Distributor Report - Detail Pages

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#22]
Remove the following detail pages from Distributor License:

- Change History Details
- Conference Details
- File Tracking Details
- License Conditions Details

![image](https://user-images.githubusercontent.com/4129185/52587745-b141b400-2e08-11e9-89cf-2881e735fe9e.png)

**Comment by calequin** [comment]
fixed issue in dev

**Comment by ABonomo21** [comment]
detail pages are still appearing in test-AW
![image](https://user-images.githubusercontent.com/47611580/54755284-0ddc7f80-4bbc-11e9-850b-6013880b4365.png)

**Comment by ABonomo21** [comment]
fixed
