### ISSUE TITLE
PLANNING - PREPLAT

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#283]
Narrow down review results
PP237626
![image](https://user-images.githubusercontent.com/4129185/54221749-7e074900-44ca-11e9-965a-ca6ad57d7ab0.png)
![image](https://user-images.githubusercontent.com/4129185/54221823-970ffa00-44ca-11e9-801d-d2cb82bdd59a.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
PP237651.  Not fixed.  DPZ was fine but all other agencies still have the long list of status options


![image](https://user-images.githubusercontent.com/4129185/54303674-e83aef00-4599-11e9-97e5-4eaa0cee69a8.png)
