### ISSUE TITLE
Planning-Plat-combined prelim/final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#339]
added hearing before first review cycle but after approving all reviews it moved to awaiting paperwork milestone.  did not stop at hearing

![image](https://user-images.githubusercontent.com/4129185/54381998-6fa16480-4665-11e9-846b-3261789bbc7c.png)

![image](https://user-images.githubusercontent.com/4129185/54381964-63b5a280-4665-11e9-9e0a-4a2ed9a055a3.png)

**Comment by dhenry-KCI** [comment]
see, went to closed w/out resolving the hearing

![image](https://user-images.githubusercontent.com/4129185/54382349-31f10b80-4666-11e9-9934-e77e752b1d04.png)

**Comment by megisys** [comment]
Resolved.. Small Issue fixed

**Comment by dhenry-KCI** [comment]
not resolved.  

![image](https://user-images.githubusercontent.com/4129185/54631324-2466c780-4a52-11e9-8841-1f7f7e83c53d.png)

![image](https://user-images.githubusercontent.com/4129185/54631346-321c4d00-4a52-11e9-804b-db6f7ac73ab6.png)

**Comment by megisys** [comment]
Mike you didnt update the application to need FCPC APP on the detail page.

![image](https://user-images.githubusercontent.com/47392306/54997752-cf233c80-4fa2-11e9-9198-0afbaa8057d9.png)

**Comment by dhenry-KCI** [comment]
ok per PL238921
