### ISSUE TITLE
Building - Major Grading - Prior to saving information

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#358]
After entering all the information needed under mitigation items the section complete box is no longer showing due to the number of items on the checklist. This needs to be moved further down the page due to multiple items being listed on applications.

logged by tiffany martin 3/15/19

![image](https://user-images.githubusercontent.com/4129185/54450523-f702dc80-4726-11e9-89aa-74af35a56384.png)

![image](https://user-images.githubusercontent.com/4129185/54450558-10a42400-4727-11e9-864a-bc30efc3b1b1.png)
The above is after we deleted a few items from the mitigation list

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
STILL NOT CORRECTED 3/26/19

![image](https://user-images.githubusercontent.com/4129185/55024031-69e83f00-4fd4-11e9-8b32-afd262e9bc12.png)

**Comment by goggansd** [comment]
Fixed in IPSTest. Please retest.

**Comment by dhenry-KCI** [comment]
corrected 4/2/19 tm

**Comment by ABonomo21** [comment]
6/20/19- Issue re-appeared. The section complete is supposed to react to number of the items

![image](https://user-images.githubusercontent.com/47611580/59870429-88f03600-9363-11e9-83cb-d8538a7ee388.png)

6/20/19 EP

**Comment by goggansd** [comment]
Looks like the only fix is to move the Section Complete box above the grid. Fixed in IPSTest.

**Comment by ABonomo21** [comment]
Thank you. Moving the details complete to the top works fine.  Ready to deploy.

6/25/19 EP
