### ISSUE TITLE
Temporary Trailer-Incorrect Reviews

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#549]
The reviews for a temporary trailer generated incorrectly. The Health Review did not generate, even though it should have according to air table. (See issue #548 ) The DUSWMF review generated when it should not have.-AW

#239014
![image](https://user-images.githubusercontent.com/47611580/54925310-6b3a3e80-4ee4-11e9-860c-f5a71d27e50f.png)

**Comment by megisys** [comment]
fixed

**Comment by ABonomo21** [comment]
partially fixed-the DUSWMF review did not generate, but the Health Dept review did not generate when it should-AW
![image](https://user-images.githubusercontent.com/47611580/55022098-43c0a000-4fd0-11e9-8835-047a41d59427.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55495938-f8c80d80-560b-11e9-91f2-b850645fe4b5.png)
