### ISSUE TITLE
PLANNING - BOA - FLDANAREA Description Error

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#578]
When creating a BOA application the FLDANAREA Work Type Description is incorrect. The Description should read "FLOOD PLAIN OR DANGER REACH AREA".

![image](https://user-images.githubusercontent.com/31770504/55027823-930ccd80-4fdc-11e9-98a7-6f967b835382.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
fixed-MW

**Comment by JuanitaMiles** [comment]
FLDANAREA Description is not fixed. It still says Danger "Beach" Area. It should say Danger Reach Area.

![image](https://user-images.githubusercontent.com/31770504/58199400-61437a80-7c9e-11e9-8a1d-5c07ea75eb91.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58963817-d5405100-877b-11e9-85f5-39b389656057.png)

Not Fixed - Description is still incorrect and should not mention BEACH

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58965449-a081c900-877e-11e9-80d6-ec9dbe146e36.png)

Fixed - AP # 244580
KEV
