### ISSUE TITLE
R4C - Distributor Report- Fee Payment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#660]
Unable to pay distributor reporting fee online

![image](https://user-images.githubusercontent.com/47611580/55650191-0cfa3f00-57b3-11e9-9b7e-0f0d9b54975f.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by ABonomo21** [comment]
still not able to pay the fee online- 

![image](https://user-images.githubusercontent.com/47611580/56831171-6dbaeb80-6836-11e9-81e4-99371641c62d.png)

**Comment by goggansd** [comment]
![image](https://user-images.githubusercontent.com/28841997/56835137-60efc500-6841-11e9-9bbd-799c7169ac98.png)
![image](https://user-images.githubusercontent.com/28841997/56835390-16bb1380-6842-11e9-897a-48f77538dcb6.png)
![image](https://user-images.githubusercontent.com/28841997/56835410-26d2f300-6842-11e9-9db8-18b81f21e9ec.png)
![image](https://user-images.githubusercontent.com/28841997/56835459-466a1b80-6842-11e9-8fb1-ce4dc06f99df.png)

**Comment by goggansd** [comment]
Not sure how the fix I did initially got undone, but I did the same thing again, and above are the test results. Please retest.

**Comment by ABonomo21** [comment]
corrected fee can be paid online
