### ISSUE TITLE
ResBLDG-ADU- Impact fees did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#703]
ADU permits are issuing without the Library impact fee and/or the school impact fees generating after the reviews and before the issuance.-AW
![image](https://user-images.githubusercontent.com/47611580/56219390-a4be1f80-6034-11e9-8370-6c90715af65c.png)

#240387-under 800 sq ft-should only have library impact fee
![image](https://user-images.githubusercontent.com/47611580/56218449-ff567c00-6032-11e9-91dd-88098cc95995.png)
#240389-over 800 sq ft-should have library and school impact fees
![image](https://user-images.githubusercontent.com/47611580/56219252-6d4f7300-6034-11e9-9eb4-7e22f763ebbf.png)

**Comment by ABonomo21** [comment]
less than 800 sq ft-not fixed

**Comment by goggansd** [comment]
Addressed in IPSTest environment. See AP # 240471.

**Comment by ABonomo21** [comment]
not fixed-aw

The permit @goggansd referenced has the incorrect impact fees. the address he chose of 804 Montclaire ave is in the City of Frederick, for which we would not accept an building permit for. The impact fee on that permit is the City Library Impact fee. This fee is would not be applicable to any permit that is within the county of Frederick.
![image](https://user-images.githubusercontent.com/47611580/56967290-e8ce1b80-6b2e-11e9-85e6-a2e26273b3b4.png)

My Test Permits-AW
#240512-less than 800 sq ft-Library impact fees did not generate and permit issued.
![image](https://user-images.githubusercontent.com/47611580/56967323-fb485500-6b2e-11e9-8cb4-e510d2b3cb16.png)

**Comment by ABonomo21** [comment]
Fixed-AW
less than 800 sq ft
![image](https://user-images.githubusercontent.com/47611580/57031455-c5ca6700-6c15-11e9-809b-ddc77d3f40d9.png)

over 800 sq ft

![image](https://user-images.githubusercontent.com/47611580/57032280-ff9c6d00-6c17-11e9-82c0-76f537e60c78.png)
