### ISSUE TITLE
Planning - Automatic Assignments - Verify 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#740]
VP239305 - Lot of Record Determination LORDET should have assigned to CTerry.  Nothing to specify LORDET in review assignment line. Not all VERIFY go to CTERRY only LORDET and PSRVER
AReed
![image](https://user-images.githubusercontent.com/4129185/56365690-76208000-61bf-11e9-95cc-433b69eb6305.png)
![image](https://user-images.githubusercontent.com/4129185/56365721-87698c80-61bf-11e9-96f1-e8b47fc63624.png)
![image](https://user-images.githubusercontent.com/4129185/56365814-baac1b80-61bf-11e9-92f9-0bb951e1b5ab.png)

**Comment by dhenry-KCI** [comment]
Also not working for FRO. Areed

![image](https://user-images.githubusercontent.com/4129185/56366714-c00a6580-61c1-11e9-8c89-3bd8b58f0755.png)
![image](https://user-images.githubusercontent.com/4129185/56366727-c8fb3700-61c1-11e9-95f9-ffbac89fbcb6.png)
![image](https://user-images.githubusercontent.com/4129185/56366871-124b8680-61c2-11e9-9001-90eb16acefec.png)

**Comment by dhenry-KCI** [comment]
NID also not working. Should assign to RBurns. Areed
![image](https://user-images.githubusercontent.com/4129185/56436052-94ae7600-62a8-11e9-9033-0a7db370bf2b.png)
![image](https://user-images.githubusercontent.com/4129185/56436074-a7c14600-62a8-11e9-9126-8427753404b6.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
NID still not being assigned to RBurns

![image](https://user-images.githubusercontent.com/4129185/57028733-d545b200-6c0d-11e9-8672-561dc01598e6.png)

**Comment by dhenry-KCI** [comment]
done 5/1

MW
