### ISSUE TITLE
Planning-NID-result of N/A remains in intake review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#822]
resulting review as N/A doesnt stage progress.  Used this result on an application i submitted through R4C.  Purposely selected a city property. Tried to use the N/A result and a comment as a way of completing the application and making applicant aware to contact the city.  But there could be times someone submits an NID when they dont need one, which could be resulted in N/A

![image](https://user-images.githubusercontent.com/4129185/57098029-237ab400-6ce7-11e9-9daa-b612e97db0d6.png)

MW

**Comment by goggansd** [comment]
Addressed in PISTest environment.

**Comment by dhenry-KCI** [comment]
not fixed

![image](https://user-images.githubusercontent.com/4129185/57227917-85d1fe00-6fe0-11e9-8a06-1e4dddbf0a03.png)

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/57228028-d0537a80-6fe0-11e9-86aa-6213867ea942.png)

**Comment by dhenry-KCI** [comment]
fixed in test-MW

![image](https://user-images.githubusercontent.com/4129185/59459159-1c68ba80-8dea-11e9-8797-d3474e8e16a9.png)
