### ISSUE TITLE
R4C-Gaming-Distributor Reports

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#941]
For the "Value of Bag" we need to have the value of "With a Projected Profit of $1101 or more." and we need to have the Issuance Fee of the bags added next to that category.-AW
Current Report:
![image](https://user-images.githubusercontent.com/47611580/58123421-c1bcb400-7bd9-11e9-9109-21378a0cb1c3.png)
in R4C:
![image](https://user-images.githubusercontent.com/47611580/58123444-d1d49380-7bd9-11e9-84f2-9ef598cf1b05.png)

**Comment by megisys** [comment]
Fixed in PreProd. Test when Environment is pointing to R4C later this week.

**Comment by ABonomo21** [comment]
retest failed. 

We need to be able to enter the quantity as dollars for over 1101

Also- the value of bag doesn't has a dollar sign before the 1101

![image](https://user-images.githubusercontent.com/47611580/58807208-a7290880-85e5-11e9-8167-57afa4b614e2.png)

**Comment by calequin** [comment]
added new column. fixed in preprod
![image](https://user-images.githubusercontent.com/47603568/59242082-df28e080-8bcf-11e9-9ae3-f59adaa46ce4.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/59294128-b1cf4780-8c4e-11e9-900c-555631b78ad2.png)

**Comment by ABonomo21** [comment]
Still missing the Issuance Fee box on the details page-AW
![image](https://user-images.githubusercontent.com/47611580/62075102-36cbeb80-b212-11e9-960d-dc5c879c8e25.png)

**Comment by megisys** [comment]
It in the background connected to the Projected Profits.

**Comment by ABonomo21** [comment]
okay to not have the bag value - AB 7.30.19
